export const ErrorCodes = {
  XML_NOT_DOWNLOADED: "XML_NOT_DOWNLOADED",
  CAPTCHA_DETECTED: "CAPTCHA_DETECTED",
  PORTAL_RETURNED_ERROR: "PORTAL_RETURNED_ERROR",
  CREDENTIALS_INVALID: "CREDENTIALS_INVALID",
  DEV_BILLING_AUTH_BYPASS_FORBIDDEN: "DEV_BILLING_AUTH_BYPASS_FORBIDDEN"
};
